#!/bin/sh

pivot() {
    local rw_root="$1"
    local work_dir="$2"
    /bin/mount \
        -o noatime,lowerdir=/,upperdir=${rw_root},workdir=${work_dir} \
        -t overlay \
        "overlayfs:${rw_root}" \
        /mnt
    pivot_root /mnt /mnt/rom
}

apply_overlay() {
    /bin/mount -t tmpfs -o noatime,mode=0755 tmpfs /overlay
    mkdir -p /overlay/root /overlay/work
    pivot /overlay/root /overlay/work
}

apply_overlay

exec /usr/sbin/init $@