name: Auto approve some PRs

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check eligibility
        id: eligibility
        run: |
          set -eux -o pipefail

          if [[ ${{ github.event.pull_request.base.repo.full_name }} != ${{ github.event.pull_request.head.repo.full_name }} ]]; then
            echo "Forked"
            exit 78
          fi

          if [[ ! ${{ github.event.pull_request.head.ref }} =~ ^bot/ ]]; then
            echo "Not in bot folder"
            exit 78
          fi

          changes=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          if [$? -ne 0 ]; then
            echo "Failed to get diff"
            exit 78
          fi

          # check if PR touches files other than SOURCE_DATE_EPOCH
          if [[ $(echo ${changes} | grep -v SOURCE_DATE_EPOCH) ]]; then
            echo "Not only SOURCE_DATE_EPOCH"
            exit 78
          fi

      - name: Approve PR
        run: gh pr review --approve --body "Auto-Approve" $PR_NUM
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
